### ISSUE TITLE
团队的任务计划

### ISSUE THREAD

**Issue by berubou** [SilentlyWatching/CourseManagement#3]
未来十天~~被强行的~~冲刺计划如下
- 争取做出个尽量完善的α版本
- 因为金工实习原因，专业课都调整到晚上。所以除了周末外不会进行任何的代码活动
- 每天晚上课后的零散时间会用来进行各种设计的讨论
- 10.30早上考试后如无意外下午会有空闲时间，此时开始至周末结束进行代码的编写。
- 第二周前两天讨论已完成代码
- 后两天继续设计
- 剩下视课程情况安排

**Comment by fanfeilong** [comment]
请细化issuse，太粗略了
